version: '3.4'
services:
  edgenuitymssql:
    image: "${DOCKER_REGISTRY}:${TAG}"    
    ports:
     - "1433:1433"
    environment: 
      SA_PASSWORD: "testus!er2017"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    build:
      context: .
      dockerfile: Dockerfile

  mongodb:
    image: mongo
    restart: always
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ""
      ME_CONFIG_MONGODB_ADMINPASSWORD: ""
      ME_CONFIG_MONGODB_SERVER: "mongodb"
    depends_on: 
      - mongodb
      - edgenuitymssql

  redis:
    image: redis
    ports:
      - "6379:32769"
